#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

polybar main &
polybar second &
feh --bg-center Downloads/346690.jpg &
flameshot &

bspc monitor DP-0 -d A C B D
bspc monitor HDMI-0 -d C D

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xrandr --output DP-0 --rate 144 --mode 2560x1080 --primary
wmname LG3D
